Update rx_message_handler.py (#1)
* Update rx_message_handler.py

TypeError: decrypt_packet() missing 1 required positional argument: 'key'

* remove bad and duplicate code